# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUAK97hRAxsgulxDh1yb6gwqF0QPV3qI
"""

import streamlit as st
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model

# ----------------------------
# Page Configuration
# ----------------------------
st.set_page_config(
    page_title="Gender Classification",
    page_icon="🧑",
    layout="centered"
)

# ----------------------------
# Load Model
# ----------------------------
model = load_model("binary_image_classifier.keras")

classes = ["Female", "Male"]

# ----------------------------
# Sidebar
# ----------------------------
st.sidebar.title("📌 About Project")

st.sidebar.info("""
### Gender Classification using CNN

This application predicts whether the uploaded face image belongs to a:

- 👨 Male
- 👩 Female

**Model:** Convolutional Neural Network (CNN)

**Framework:** TensorFlow & Streamlit
""")

# ----------------------------
# Main Title
# ----------------------------
st.markdown(
    """
    <h1 style='text-align:center;color:#4F46E5;'>
    🧑 Gender Classification using CNN
    </h1>
    """,
    unsafe_allow_html=True
)

st.markdown(
    "<p style='text-align:center;'>Upload a face image and let the CNN model predict the gender.</p>",
    unsafe_allow_html=True
)

st.divider()

# ----------------------------
# Upload Image
# ----------------------------
uploaded_file = st.file_uploader(
    "📤 Upload Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Uploaded Image",
        width=300
    )

    img = image.resize((150,150))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img)

    if prediction[0][0] > 0.5:
        label = classes[1]
        confidence = prediction[0][0]
        emoji = "👨"
    else:
        label = classes[0]
        confidence = 1-prediction[0][0]
        emoji = "👩"

    st.divider()

    st.markdown("## 🎯 Prediction Result")

    st.success(f"{emoji} **Predicted Gender:** {label}")

    st.write(f"### Confidence: **{confidence*100:.2f}%**")

    st.progress(float(confidence))

    if confidence > 0.90:
        st.success("The model is highly confident about this prediction.")
    elif confidence > 0.70:
        st.info("The model is reasonably confident.")
    else:
        st.warning("The prediction confidence is relatively low.")

st.divider()

st.markdown("""
### 💡 Instructions
- Upload a clear face image.
- Supported formats: JPG, JPEG, PNG.
- Best results are obtained with front-facing images.
""")

st.caption("Developed using ❤️ Streamlit & TensorFlow")